name: Build

on:
  push:
    branches:
      - deploy-to-ec2

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Tests
        run: mvn clean test

  build:
    runs-on: ubuntu-latest
    needs: test # Run only if tests pass

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: |
          mvn clean package # Build JAR
          find target -name "*.jar"
          
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: target/*.jar


