name: Install packages to EC2

on:
  push:
    branches: 
      -  deploy-to-ec2
      -  main

  workflow_dispatch:

jobs:
  install_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java and Maven on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update package lists
            sudo apt update
            echo "✅ Updated packages list"
            
            # Install Java 17 & Maven
            sudo apt install -y --no-install-recommends openjdk-17-jdk maven
            echo "✅ Java & Maven Installed"

            # Verify installations
            java -version
            mvn -version
